### ISSUE TITLE
Fehlende lang-Texte hinterlegen

### ISSUE THREAD

**Issue by alxndr-w** [alexplusde/stellenangebote#30]
![image](https://github.com/alexplusde/stellenangebote/assets/3855487/84e93104-d3b9-4c8e-8738-498d5b493cf9)

**Comment by alxndr-w** [comment]
![image](https://github.com/alexplusde/stellenangebote/assets/3855487/6d41e6ba-19ae-4f26-a96f-07dae69a1318)

**Comment by schorschy** [comment]
https://github.com/alexplusde/stellenangebote/pull/31
